# Generated by Django 2.1.3 on 2018-11-28 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServisRapor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servisrapor',
            name='rapor_saha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musteri.Saha'),
        ),
    ]
