# Generated by Django 2.1.3 on 2018-12-02 12:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ServisRapor', '0002_auto_20181128_0738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servisrapor',
            name='rapor_musteri',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musteri.Musteri', verbose_name='Müşteri'),
        ),
        migrations.AlterField(
            model_name='servisrapor',
            name='rapor_saha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musteri.Saha', verbose_name='Müşteri Saha'),
        ),
        migrations.AlterField(
            model_name='servisrapor',
            name='servis_personel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Servis Personeli'),
        ),
        migrations.AlterField(
            model_name='servisrapor',
            name='servis_pompa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ServisRapor.Pompa', verbose_name='Pompa'),
        ),
    ]
