# Generated by Django 2.1.3 on 2018-12-02 15:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ServisRapor', '0003_auto_20181202_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servisrapor',
            name='servis_talep_tarih',
        ),
        migrations.AddField(
            model_name='pompa',
            name='servis_pompa_guc_birim',
            field=models.CharField(blank=True, choices=[('kw', 'kW'), ('mw', 'MW'), ('hp', 'HP')], max_length=2, null=True, verbose_name='Motor Güç Birimi'),
        ),
        migrations.AlterField(
            model_name='pompa',
            name='servis_pompa_fan_capi',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)], verbose_name='Fan Çapı [mm]'),
        ),
        migrations.AlterField(
            model_name='pompa',
            name='servis_pompa_verim',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Verim (%)'),
        ),
        migrations.AlterField(
            model_name='servisrapor',
            name='servis_rapor_no',
            field=models.CharField(blank=True, max_length=13, verbose_name='Rapor No'),
        ),
        migrations.AlterField(
            model_name='servisrapor',
            name='toplam_mesafe',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(2040)], verbose_name='Toplam Mesafe [Km]'),
        ),
    ]
