# Generated by Django 2.1.3 on 2018-12-02 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServisRapor', '0005_auto_20181202_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pompa',
            old_name='servis_pompa_akiskan_sicaklık',
            new_name='servis_pompa_akiskan_sicaklik',
        ),
        migrations.RenameField(
            model_name='pompa',
            old_name='servis_pompa_uretim_yıl',
            new_name='servis_pompa_uretim_yil',
        ),
        migrations.RenameField(
            model_name='servisrapor',
            old_name='flator_baglantı',
            new_name='flator_baglanti',
        ),
    ]
