# Generated by Django 2.1.3 on 2018-11-23 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Arac',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac_plaka', models.CharField(max_length=8, unique=True, verbose_name='Araç Plakası')),
                ('arac_model', models.CharField(max_length=25, verbose_name='Araç Modeli')),
                ('arac_sigorta_tarih', models.DateTimeField(verbose_name='Araç Sigorta Tarihi')),
                ('arac_muayene_tarih', models.DateTimeField(verbose_name='Araç Muayene Tarihi')),
                ('arac_bakim_tarih', models.DateTimeField(verbose_name='Araç Bakım Tarihi')),
            ],
            options={
                'verbose_name': 'Araç',
                'verbose_name_plural': 'Araçlar',
            },
        ),
        migrations.CreateModel(
            name='AracKullanim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arac_alis_tarih', models.DateTimeField(verbose_name='Araç Alış Tarihi')),
                ('arac_teslim_tarihi', models.DateTimeField(verbose_name='Araç Teslim Tarihi')),
                ('arac_teslim_km', models.DateTimeField(verbose_name='Teslim KM')),
                ('arac_surucu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Araç Sürücüsü')),
            ],
            options={
                'verbose_name': 'Araç Kullanımı',
                'verbose_name_plural': 'Araç Kullanımları',
            },
        ),
    ]
