# Generated by Django 2.1.3 on 2018-11-23 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Arac', '0002_auto_20181123_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='arackullanim',
            name='arac_kullanim',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='Arac.Arac', verbose_name='Kullandığı Araç'),
        ),
    ]
