# Generated by Django 2.1.3 on 2018-11-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arac', '0003_arackullanim_arac_kullanim'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arackullanim',
            name='arac_teslim_km',
            field=models.IntegerField(verbose_name='Teslim KM'),
        ),
    ]
