# Generated by Django 2.1.3 on 2018-11-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arac', '0004_auto_20181123_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arac',
            name='arac_plaka',
            field=models.CharField(max_length=11, unique=True, verbose_name='Araç Plakası'),
        ),
    ]
