# Generated by Django 2.1.3 on 2018-11-28 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arac', '0006_arac_arac_ego_tarih'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arac',
            name='arac_bakim_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Araç Bakım Tarihi'),
        ),
        migrations.AlterField(
            model_name='arac',
            name='arac_muayene_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Araç Muayene Tarihi'),
        ),
        migrations.AlterField(
            model_name='arac',
            name='arac_sigorta_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Araç Sigorta Tarihi'),
        ),
    ]
