# Generated by Django 2.1.3 on 2018-11-29 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Musteri', '0002_auto_20181128_1609'),
        ('Arac', '0007_auto_20181128_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='arackullanim',
            name='arac_saha_dest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Musteri.Saha', verbose_name='Aracın Gittiği Saha'),
        ),
        migrations.AlterField(
            model_name='arac',
            name='arac_ego_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Araç Ego Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='arac',
            name='arac_muayene_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Araç Muayene Bitiş Tarihi'),
        ),
        migrations.AlterField(
            model_name='arac',
            name='arac_sigorta_tarih',
            field=models.DateField(blank=True, null=True, verbose_name='Araç Sigorta Bitiş Tarihi'),
        ),
    ]
