# Generated by Django 2.1.3 on 2018-11-29 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Arac', '0009_auto_20181129_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arackullanim',
            name='arac_teslim_km',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500000)], verbose_name='Teslim KM'),
        ),
    ]
