# Generated by Django 2.1.3 on 2018-11-21 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PompaModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pompamodel',
            name='pompa_bi_kitapcigi',
            field=models.FileField(null=True, upload_to='Bakim_İsletme/'),
        ),
        migrations.AddField(
            model_name='pompamodel',
            name='pompa_patlamis',
            field=models.FileField(null=True, upload_to='Patlamis/'),
        ),
        migrations.AddField(
            model_name='pompamodel',
            name='pompa_resim',
            field=models.ImageField(null=True, upload_to='Pompa_Resimleri/'),
        ),
        migrations.AddField(
            model_name='pompamodel',
            name='pompa_tip_kitapcigi',
            field=models.FileField(null=True, upload_to='Tip/'),
        ),
    ]
