# Generated by Django 2.1.3 on 2018-11-28 06:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PompaModel', '0003_auto_20181121_1321'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pompamodel',
            old_name='pompa',
            new_name='pompa_model',
        ),
    ]
