# Generated by Django 2.1.3 on 2018-11-30 12:32

import PompaModel.utilities
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PompaModel', '0004_auto_20181128_0659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pompamodel',
            name='pompa_bi_kitapcigi',
            field=models.FileField(blank=True, null=True, upload_to=PompaModel.utilities.pompa_bi_isimlendirme, verbose_name='Bakım İşletme Kitapçığı'),
        ),
        migrations.AlterField(
            model_name='pompamodel',
            name='pompa_patlamis',
            field=models.FileField(blank=True, null=True, upload_to=PompaModel.utilities.pompa_patlamis_isimlendirme, verbose_name='Patlamış Resim'),
        ),
        migrations.AlterField(
            model_name='pompamodel',
            name='pompa_resim',
            field=models.ImageField(null=True, upload_to=PompaModel.utilities.pompa_resim_isimlendirme, verbose_name='Pompa Resmi'),
        ),
        migrations.AlterField(
            model_name='pompamodel',
            name='pompa_tip_kitapcigi',
            field=models.FileField(blank=True, null=True, upload_to=PompaModel.utilities.pompa_tip_isimlendirme, verbose_name='Tip Kitapçığı'),
        ),
    ]
