# Generated by Django 2.1.3 on 2018-11-23 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Musteri',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_adi', models.CharField(max_length=60, verbose_name='Firma Adı')),
                ('firma_adresi', models.TextField(max_length=200, verbose_name='Firma Adresi')),
            ],
            options={
                'verbose_name': 'Müşteri',
                'verbose_name_plural': 'Müşteriler',
            },
        ),
        migrations.CreateModel(
            name='Saha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saha_adi', models.CharField(max_length=30, verbose_name='Saha Adı')),
                ('saha_adresi', models.TextField(max_length=200, verbose_name='Saha Adresi')),
                ('saha_ilgili', models.CharField(max_length=25, verbose_name='Saha İlgilisi')),
                ('saha_ilgili_tel', models.CharField(max_length=12, verbose_name='İlgili Tel.')),
                ('saha_ilgili_eposta', models.EmailField(max_length=254, null=True, verbose_name='İlgili E-Posta')),
                ('musteri_saha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Musteri.Musteri')),
            ],
            options={
                'verbose_name': 'Saha',
                'verbose_name_plural': 'Sahalar',
            },
        ),
    ]
