# Generated by Django 2.1.3 on 2018-11-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Musteri', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saha',
            name='saha_ilgili',
        ),
        migrations.RemoveField(
            model_name='saha',
            name='saha_ilgili_eposta',
        ),
        migrations.RemoveField(
            model_name='saha',
            name='saha_ilgili_tel',
        ),
    ]
