# Generated by Django 2.1.3 on 2018-11-23 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('PompaModel', '0003_auto_20181121_1321'),
    ]

    operations = [
        migrations.CreateModel(
            name='Talep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('talep_no', models.CharField(max_length=6, verbose_name='Talep No')),
                ('firma_adi', models.CharField(max_length=60, verbose_name='Firma Adı')),
                ('talep_yetkili', models.CharField(max_length=30, verbose_name='Talep Yetkilisi')),
                ('talep_yetkili_tel', models.CharField(max_length=12, verbose_name='Yetkili Telefonu')),
                ('talep_pompa_tipi', models.CharField(blank=True, max_length=20, null=True, verbose_name='Pompa Tipi')),
                ('talep_pompa_serino', models.CharField(max_length=20, verbose_name='Pompa Seri No')),
                ('talep_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='Talep Tarihi')),
                ('enerji_kontrol', models.BooleanField(default=False, verbose_name='Enerji Kontrolleri')),
                ('akiskan_kontrol', models.BooleanField(default=False, verbose_name='Akışkan Kontrolleri')),
                ('personel', models.BooleanField(default=False, verbose_name='Yardımcı Personel')),
                ('sizdirmazlik', models.BooleanField(default=False, verbose_name='Tesisat Sızdırmazlık Testi')),
                ('pompa_hazir', models.BooleanField(default=False, verbose_name='Pompa Hazır')),
                ('on_hazirlik', models.BooleanField(default=False, verbose_name='Kitapçık Ön Hazırlık')),
                ('betonlama', models.BooleanField(default=False, verbose_name='Grout Betonlama')),
                ('is_sagligi', models.BooleanField(default=False, verbose_name='İş Sağlığı Tedbirleri')),
                ('talep_org_tarihi', models.DateField(verbose_name='Organizasyon Tarih Talebi')),
                ('yetkili_onayi', models.BooleanField(default=False, verbose_name='Yetkili Onay')),
                ('talep_pompa_adi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PompaModel.PompaModel')),
            ],
            options={
                'verbose_name': 'Servis Talebi',
                'verbose_name_plural': 'Servis Talepleri',
            },
        ),
    ]
