# Generated by Django 2.1.3 on 2018-12-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Talep', '0003_auto_20181128_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='talep',
            name='yetkili_onayi',
            field=models.BooleanField(default=False, verbose_name='Yetkili Onayı'),
        ),
    ]
